export const posts = [
    {
      id: 1,
      username: "john_doe",
      profileImage: "https://i.pravatar.cc/150?img=1",
      postImage: "https://picsum.photos/600/600?random=10",
      caption: "Beautiful day with beautiful vibes ✨",
      likes: 124,
      comments: 18,
      time: "2 hours ago",
    },
    {
      id: 2,
      username: "sarah_khan",
      profileImage: "https://i.pravatar.cc/150?img=2",
      postImage: "https://picsum.photos/600/600?random=11",
      caption: "Enjoying the little moments 🌸",
      likes: 256,
      comments: 32,
      time: "4 hours ago",
    },
    {
      id: 3,
      username: "alex_wilson",
      profileImage: "https://i.pravatar.cc/150?img=3",
      postImage: "https://picsum.photos/600/600?random=12",
      caption: "Weekend vibes 😎",
      likes: 389,
      comments: 45,
      time: "6 hours ago",
    },
    {
      id: 4,
      username: "emma_lee",
      profileImage: "https://i.pravatar.cc/150?img=4",
      postImage: "https://picsum.photos/600/600?random=13",
      caption: "Keep smiling and keep shining ✨",
      likes: 542,
      comments: 67,
      time: "1 day ago",
    },
    {
      id: 5,
      username: "david_ali",
      profileImage: "https://i.pravatar.cc/150?img=5",
      postImage: "https://picsum.photos/600/600?random=14",
      caption: "New adventures begin here 🌍",
      likes: 198,
      comments: 24,
      time: "1 day ago",
    },
  ];
  