export const posts = [
  {
    id: 1,
    username: 'microsoftazure',
    userImage: '/php.png',
    isVerified: true,
    isAd: true,
    postImage: '/1.png',
    likes: 257,
    caption: 'No barrier to entry, no upfront commitment—try Azure for free and start building in the Cloud.',
  },
  {
    id: 2,
    username: 'john_doe',
    userImage: '/php.png',
    isVerified: false,
    isAd: false,
    postImage: '/1.png',
    likes: 1042,
    caption: 'Exploring new paths and coding through the weekend 🚀',
  },
  {
    id: 3,
    username: 'sarah_khan',
    userImage: '/php.png',
    isVerified: true,
    isAd: false,
    postImage: '/1.png',
    likes: 890,
    caption: 'Beautiful sunset moments! 🌅✨',
  },
  {
    id: 4,
    username: 'alex_wilson',
    userImage: '/php.png',
    isVerified: false,
    isAd: false,
    postImage: '/1.png',
    likes: 412,
    caption: 'Setup upgrade complete. What do you think?',
  },
  {
    id: 5,
    username: 'emma_lee',
    userImage: '/php.png',
    isVerified: true,
    isAd: false,
    postImage: '/1.png',
    likes: 3105,
    caption: 'Weekend vibes! 🍕☕',
  },
]