export const stories = [
    {
        id: 1,
        username: "john_doe",
        profileImage: "https://i.pravatar.cc/150?img=1",
        storyImage: "https://picsum.photos/400/700?random=1",
        seen: false,
    },
    {
        id: 2,
        username: "sarah_khan",
        profileImage: "https://i.pravatar.cc/150?img=2",
        storyImage: "https://picsum.photos/400/700?random=2",
        seen: false,
    },
    {
        id: 3,
        username: "alex_wilson",
        profileImage: "https://i.pravatar.cc/150?img=3",
        storyImage: "https://picsum.photos/400/700?random=3",
        seen: true,
    },
    {
        id: 4,
        username: "emma_lee",
        profileImage: "https://i.pravatar.cc/150?img=4",
        storyImage: "https://picsum.photos/400/700?random=4",
        seen: false,
    },
    {
        id: 5,
        username: "david_ali",
        profileImage: "https://i.pravatar.cc/150?img=5",
        storyImage: "https://picsum.photos/400/700?random=5",
        seen: true,
    },
    {
        id: 6,
        username: "lisa_malik",
        profileImage: "https://i.pravatar.cc/150?img=6",
        storyImage: "https://picsum.photos/400/700?random=6",
        seen: false,
    },
    {
        id: 7,
        username: "mike_jones",
        profileImage: "https://i.pravatar.cc/150?img=7",
        storyImage: "https://picsum.photos/400/700?random=7",
        seen: false,
    },
];
